// Assembles dist/clepso.css from the design-system sources: tokens (generated
// by design/src/build.py) + the component stylesheet. The web font is served
// by Google Fonts; the @import must stay first so browsers honour it.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../../..');
const tokens = readFileSync(resolve(repo, 'design/system/tokens.css'), 'utf8');
const bundle = readFileSync(resolve(repo, 'design/system/components/bundle.css'), 'utf8');
const fonts =
  '@import url("https://fonts.googleapis.com/css2?family=Geist:wght@300..700&family=Geist+Mono:wght@400..600&display=swap");\n';
const banner =
  '/* Clepso — generated by @lawfirm/ui-web scripts/build-css.mjs. Sources: design/src. */\n';
mkdirSync(resolve(here, '../dist'), { recursive: true });
writeFileSync(resolve(here, '../dist/clepso.css'), fonts + banner + tokens + '\n' + bundle);
// Same stylesheet without the Google Fonts @import, for apps that self-host Geist
// (apps/web loads it through next/font and points --font-sans at it).
writeFileSync(resolve(here, '../dist/clepso.base.css'), banner + tokens + '\n' + bundle);
console.log('dist/clepso.css + dist/clepso.base.css written');
