"""Emit the mobile/web Tailwind preset and the TypeScript token module for @lawfirm/ui from tokens.py.

  packages/ui/src/tokens.ts       — themes (light/dark) as hex + as NativeWind `vars()` maps (rgb triplets), spacing, radius, sizes, type, fonts
  packages/ui/tailwind-preset.cjs — colours as rgb(var(--x) / <alpha-value>), radius, font sizes with px tracking, font families per weight
"""
import json, os, subprocess, sys
sys.path.insert(0, os.path.dirname(__file__))
import tokens as T

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
UI = os.path.join(REPO, 'packages', 'ui')

def rgb_triplet(hex_):
    h = hex_.lstrip('#')[:6]
    return ' '.join(str(int(h[i:i + 2], 16)) for i in (0, 2, 4))

def theme(name):
    """name -> ordered {cssVar: hex} for one theme."""
    acc = T.ACCENTS[T.DEFAULT_ACCENT][name]
    out = {}
    for _n, light, dark, var, _u in T.SEMANTIC:
        out[var] = light if name == 'light' else dark
    m = {"primary": "accent", "hover": "accent-hover", "pressed": "accent-pressed", "tint": "accent-tint",
         "on-tint": "accent-ink", "on-primary": "on-accent"}
    for role, var in m.items():
        out[var] = acc[role]
    for st, v in T.STATUS.items():
        for role in ("bg", "ink", "dot", "solid", "on"):
            out[f"{st}-{role}"] = v[name][role]
    cats = T.DATAVIZ["categorical" if name == "light" else "categorical_dark"]
    for i, c in enumerate(cats, 1):
        out[f"chart-{i}"] = c
    seq = T.DATAVIZ["sequential_light" if name == "light" else "sequential_dark"]
    for i, c in enumerate(seq, 1):
        out[f"chart-seq-{i}"] = c
    return out

FONT_FAMILIES = {
    # NativeWind class suffix -> expo-google-fonts family names (static weights) with web fallbacks
    "sans": ("Geist_400Regular", '"Geist", -apple-system, "SF Pro Text", "Segoe UI", Roboto, system-ui, sans-serif'),
    "sans-medium": ("Geist_500Medium", '"Geist", -apple-system, "SF Pro Text", "Segoe UI", Roboto, system-ui, sans-serif'),
    "sans-semibold": ("Geist_600SemiBold", '"Geist", -apple-system, "SF Pro Text", "Segoe UI", Roboto, system-ui, sans-serif'),
    "mono": ("GeistMono_400Regular", '"Geist Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace'),
    "mono-medium": ("GeistMono_500Medium", '"Geist Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace'),
}

def ts_obj(d, indent=2, raw_values=False):
    pad = ' ' * indent
    fmt = (lambda v: str(v)) if raw_values else (lambda v: f"'{v}'")
    return '{\n' + ''.join(f"{pad}'{k}': {fmt(v)},\n" for k, v in d.items()) + ' ' * (indent - 2) + '}'

def build_tokens_ts():
    light, dark = theme('light'), theme('dark')
    lines = ["/**", " * Clepso design tokens — GENERATED by design/src/build.py from design/src/tokens.py.", " * Do not edit by hand; change design/src/tokens.py and rebuild.", " *",
             " * `themes.<name>` are hex values for code that needs raw colours (navigation, status bar, charts).",
             " * `themeVars.<name>` are the same colours as rgb triplets for NativeWind `vars()`; the Tailwind preset", " * maps every colour utility to `rgb(var(--x) / <alpha-value>)`, so switching the map switches the theme.", " */", ""]
    lines.append("export type ThemeName = 'light' | 'dark';")
    lines.append("")
    lines.append("export const themes = {")
    lines.append("  light: " + ts_obj(light, 4) + ",")
    lines.append("  dark: " + ts_obj(dark, 4) + ",")
    lines.append("} as const;")
    lines.append("")
    lines.append("export type ColorToken = keyof typeof themes.light;")
    lines.append("")
    lines.append("export const themeVars = {")
    lines.append("  light: " + ts_obj({f"--{k}": rgb_triplet(v) for k, v in light.items()}, 4) + ",")
    lines.append("  dark: " + ts_obj({f"--{k}": rgb_triplet(v) for k, v in dark.items()}, 4) + ",")
    lines.append("} as const;")
    lines.append("")
    lines.append("/** Default (light) colours, for code that predates theming. */")
    lines.append("export const colors = themes.light;")
    lines.append("")
    lines.append("export const spacing = " + ts_obj({n.replace('space-', ''): v for n, v in T.SPACING}, 2, raw_values=True) + " as const;")
    lines.append("")
    lines.append("export const radius = " + ts_obj({n.replace('radius-', ''): v for n, v, _u in T.RADIUS}, 2, raw_values=True) + " as const;")
    lines.append("")
    lines.append("export const sizes = " + ts_obj({n: v for n, v, _u in T.SIZES}, 2, raw_values=True) + " as const;")
    lines.append("")
    lines.append("export const fonts = {")
    for k, (native, web) in FONT_FAMILIES.items():
        lines.append(f"  '{k}': {{ native: '{native}', web: '{web}' }},")
    lines.append("} as const;")
    lines.append("")
    lines.append("/** Type scale: size / line-height in px, weight, letter-spacing in px, family key. */")
    lines.append("export const type = {")
    for name, fam, size, lh, w, ls, _u in T.TYPE_SCALE:
        ls_px = round(float(ls.replace('em', '')) * size, 2) if ls.endswith('em') else float(ls)
        family = ('mono-medium' if w >= 500 else 'mono') if fam == 'mono' else ('sans-semibold' if w >= 600 else 'sans-medium' if w >= 500 else 'sans')
        lines.append(f"  '{name}': {{ size: {size}, lineHeight: {lh}, weight: {w}, letterSpacing: {ls_px}, family: '{family}' }},")
    lines.append("} as const;")
    lines.append("")
    lines.append("export type TypeStyle = keyof typeof type;")
    lines.append("")
    lines.append("export const motion = " + ts_obj({n.replace('duration-', '').replace('ease-', 'ease-'): v for n, v, _u in T.MOTION}, 2) + " as const;")
    lines.append("")
    return "\n".join(lines) + "\n"

def build_preset():
    light = theme('light')
    color_entries = []
    for var in light:
        color_entries.append(f"      '{var}': 'rgb(var(--{var}) / <alpha-value>)',")
    fs = []
    for name, fam, size, lh, w, ls, _u in T.TYPE_SCALE:
        ls_px = round(float(ls.replace('em', '')) * size, 2) if ls.endswith('em') else float(ls)
        fs.append(f"      '{name}': ['{size}px', {{ lineHeight: '{lh}px', letterSpacing: '{ls_px}px' }}],")
    ff = []
    for k, (native, web) in FONT_FAMILIES.items():
        fam = [native] + [f.strip().strip('"') for f in web.split(',')]
        ff.append(f"      '{k}': [{', '.join(json.dumps(f) for f in fam)}],")
    radius = "\n".join(f"      {n.replace('radius-', '')}: '{v}px'," for n, v, _u in T.RADIUS)
    return f"""/**
 * Clepso Tailwind preset — GENERATED by design/src/build.py from design/src/tokens.py.
 * Consumed by apps/mobile (NativeWind 4) and later apps/web (Tailwind).
 * Weight is carried by the font family (Geist_600SemiBold…), never by fontWeight, so no platform synthesises bold.
 * Colours resolve through CSS variables so one class set serves light and dark:
 * the app applies `vars(themeVars.light | themeVars.dark)` from @lawfirm/ui at its root.
 */
module.exports = {{
  theme: {{
    extend: {{
      colors: {{
{chr(10).join(color_entries)}
      }},
      borderRadius: {{
{radius}
      }},
      fontFamily: {{
{chr(10).join(ff)}
      }},
      fontSize: {{
{chr(10).join(fs)}
      }},
    }},
  }},
}};
"""

def main():
    with open(os.path.join(UI, 'src', 'tokens.ts'), 'w') as f:
        f.write(build_tokens_ts())
    with open(os.path.join(UI, 'tailwind-preset.cjs'), 'w') as f:
        f.write(build_preset())
    prettier = os.path.join(REPO, 'node_modules', '.bin', 'prettier')
    if os.path.exists(prettier):
        subprocess.run([prettier, '--write', os.path.join(UI, 'src', 'tokens.ts'), os.path.join(UI, 'tailwind-preset.cjs'), '--log-level', 'warn'], check=False)
    print('packages/ui tokens.ts + tailwind-preset.cjs written')

if __name__ == '__main__':
    main()
